version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nestjs_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "${PORT}:${PORT}"

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

volumes:
  postgres_data:
